sudo: false
dist: trusty
language: generic

cache:
  directories:
    - $HOME/.stack/

addons:
  apt:
    packages:
      - libgmp-dev
      - libgl1-mesa-dev
      - libxi-dev
      - libxcursor-dev
      - libxinerama-dev
      - libxrandr-dev
      - zlib1g-dev
      - libpulse-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack update
  - stack --no-terminal --install-ghc test --only-dependencies -j3

script:
  - stack --no-terminal build -j3
