resolver: lts-9.0
flags: {}
packages:
- '.'
- location:
    git: https://github.com/lambdacube3d/lambdacube-ir.git
    commit: a0bf64b83dd218d1ea29823749dcfa8a6ee959a9
  subdirs:
    - lambdacube-ir.haskell
  extra-dep: true
- location:
    git: https://github.com/lambdacube3d/lambdacube-gl.git
    commit: 297dfbf6f633a1269640b92ebc55b05ca58c102f
  extra-dep: true
- location:
    git: https://github.com/lambdacube3d/lambdacube-compiler.git
    commit: 132ccb3423c8c181bed8dc2219ad42091f485213
  extra-dep: true
extra-deps:
  - proteaaudio-0.7.0.1
  - vect-0.4.7
  - wavefront-0.7.1
